#pragma once

#define MAX_PATH 260
#define DRIVER_NAME L"Lab_5_2"
#define IOCTL_UPDATE_PROCESS_LOGGER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0800, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct {
	BOOLEAN enabled;
	LARGE_INTEGER start;
	int seconds;
} PROCESS_LOGGER_OBJECT, *PPROCESS_LOGGER_OBJECT;
