#pragma once

#define MAX_PATH 260
#define DRIVER_NAME L"Lab_5_1"
#define IOCTL_UPDATE_PROCESS_WATCHER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0800, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct {
	BOOLEAN enabled;
	CHAR watchedProcess[MAX_PATH];
	CHAR followedProcess[MAX_PATH];
} PROCESS_WATCHER_OBJECT, *PPROCESS_WATCHER_OBJECT;
